### ISSUE TITLE
Beacon question

### ISSUE THREAD

**Issue by cactushydrocodone** [jontek2/V2-1645-klipper_config#1]
Hi, nice build!

I have a question regarding the ebb36 and the beacon board.
How did you connect the beacon? Did you connect it to your EBB36 and made a USB-C cable?
Or did you connect the beacon straight to the main mcu?

Eagerly awaing your response :)

**Comment by jontek2** [comment]
Hi,

On this machine i’ve got it running with a separate wire, which is included with the beacon. So basically I’ve got two umbilicals running; one for the ebb36 and one of the beacon.

On my trident machine I’ve made a custom 8-wire cable that’s has both CAN and beacon wires in it.

To my knowledge the beacon doesn’t support CAN, only usb. But clones of the beacon like IDM/Cartographer do where you could connect it to the CAN network on the exposed CAN-pins on the ebb36.
